services:
  postgres:
    container_name: postgres
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - TZ=UTC
    image: postgres:16-alpine
    labels:
      - docker-volume-backup.stop-during-backup=true
    networks:
      - postgres_network
    ports:
      - 5436:5432
    read_only: true
    restart: unless-stopped
    security_opt:
      - apparmor:docker-default
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

networks:
  postgres_network:
    name: postgres_network

volumes:
  postgres_data:
    name: postgres_data
