REQUISITION_FILTER_FIELDS = {
    "id": ["exact", "in"],
    "name": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "external_reference": ["exact", "contains", "startswith", "endswith", "in", "regex", "isnull"],
    "status": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "owner__username": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "project__name": ["exact", "contains", "startswith", "endswith", "in", "regex", "isnull"],
    "supplier": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "justification": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "total_amount": ["exact", "gt", "gte", "lt", "lte", "range"],
    "currency": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "created_at": ["exact", "gt", "gte", "lt", "lte", "range"],
    "created_by__username": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "updated_at": ["exact", "gt", "gte", "lt", "lte", "range"],
    "updated_by__username": [
        "exact",
        "contains",
        "startswith",
        "endswith",
        "in",
        "regex",
    ],
    "submitted_at": ["exact", "gt", "gte", "lt", "lte", "range", "isnull"],
    "approved_at": ["exact", "gt", "gte", "lt", "lte", "range", "isnull"],
}


REQUISITION_LINE_FILTER_FIELDS = {
    "id": ["exact", "in"],
    "line_number": ["exact", "gt", "gte", "lt", "lte", "range"],
    "line_type": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "description": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "category": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "manufacturer": ["exact", "contains", "startswith", "endswith", "in", "regex", "isnull"],
    "manufacturer_part_number": [
        "exact",
        "contains",
        "startswith",
        "endswith",
        "in",
        "regex",
        "isnull",
    ],
    "quantity": ["exact", "gt", "gte", "lt", "lte", "range", "isnull"],
    "uom": ["exact", "contains", "startswith", "endswith", "in", "regex", "isnull"],
    "unit_price": ["exact", "gt", "gte", "lt", "lte", "range", "isnull"],
    "line_total": ["exact", "gt", "gte", "lt", "lte", "range"],
    "payment_term": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "need_by": ["exact", "gt", "gte", "lt", "lte", "range", "isnull"],
    "requisition__id": ["exact", "gt", "gte", "lt", "lte", "range"],
    "ship_to__name": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "created_at": ["exact", "gt", "gte", "lt", "lte", "range"],
    "created_by__username": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "updated_at": ["exact", "gt", "gte", "lt", "lte", "range"],
    "updated_by__username": [
        "exact",
        "contains",
        "startswith",
        "endswith",
        "in",
        "regex",
    ],
}
