ADDRESS_STRING_REQUIRED = [
    "exact",
    "iexact",
    "contains",
    "icontains",
    "startswith",
    "istartswith",
    "endswith",
    "iendswith",
    "in",
    "regex",
]

ADDRESS_STRING_OPTIONAL = [
    "exact",
    "iexact",
    "contains",
    "icontains",
    "startswith",
    "istartswith",
    "endswith",
    "iendswith",
    "in",
    "regex",
    "isnull",
]

ADDRESS_DATE = [
    "exact",
    "gt",
    "gte",
    "lt",
    "lte",
    "date",
    "range",
    "year",
    "quarter",
    "month",
    "week",
    "week_day",
    "day",
]

ADDRESS_FILTER_FIELDS = {
    "id": ["exact", "in"],
    "name": ADDRESS_STRING_REQUIRED,
    "address_code": ADDRESS_STRING_OPTIONAL,
    "description": ADDRESS_STRING_OPTIONAL,
    "attention": ADDRESS_STRING_REQUIRED,
    "phone": ADDRESS_STRING_OPTIONAL,
    "street1": ADDRESS_STRING_REQUIRED,
    "street2": ADDRESS_STRING_OPTIONAL,
    "city": ADDRESS_STRING_REQUIRED,
    "state": ADDRESS_STRING_REQUIRED,
    "zip_code": ADDRESS_STRING_REQUIRED,
    "country": ADDRESS_STRING_REQUIRED,
    "delivery_instructions": ADDRESS_STRING_OPTIONAL,
    "owner__username": ADDRESS_STRING_REQUIRED,
    "created_at": ADDRESS_DATE,
    "created_by__username": ADDRESS_STRING_REQUIRED,
    "updated_at": ADDRESS_DATE,
    "updated_by__username": ADDRESS_STRING_REQUIRED,
}
