ADDRESS_FILTER_FIELDS = {
    "id": ["exact", "in"],
    "name": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "address_code": ["exact", "contains", "startswith", "endswith", "in", "regex", "isnull"],
    "description": ["exact", "contains", "startswith", "endswith", "in", "regex", "isnull"],
    "attention": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "phone": ["exact", "contains", "startswith", "endswith", "in", "regex", "isnull"],
    "street1": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "street2": ["exact", "contains", "startswith", "endswith", "in", "regex", "isnull"],
    "city": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "state": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "zip_code": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "country": [
        "exact",
        "contains",
        "startswith",
        "endswith",
        "in",
        "regex",
    ],
    "owner__username": ["exact", "contains", "startswith", "endswith", "in", "regex"],
    "created_at": ["exact", "gt", "gte", "lt", "lte", "range"],
    "created_by__username": [
        "exact",
        "contains",
        "startswith",
        "endswith",
        "in",
        "regex",
    ],
    "updated_at": ["exact", "gt", "gte", "lt", "lte", "range"],
    "updated_by__username": [
        "exact",
        "contains",
        "startswith",
        "endswith",
        "in",
        "regex",
    ],
}
